THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1513366702650/work/torch/lib/THC/generic/THCStorage.cu line=58 error=30 : unknown error
ROOT_PATH: /home-nfs/siddsach/ml/Interpreting-Attention/interpreting_language
Building Bayesian Optimizer for 
 data:MPQA 
 choices:[{'type': 'continuous', 'domain': [5e-05, 0.005], 'name': 'lr'}, {'type': 'continuous', 'domain': [0, 1], 'name': 'rnn_dropout'}, {'type': 'continuous', 'domain': [0, 1], 'name': 'dropout'}, {'type': 'continuous', 'domain': [0, 1], 'name': 'l2'}]
SETTINGS FOR THIS RUN
{'data': 'MPQA', 'rnn_dropout': 0.5183626113550769, 'wordvec_dim': 300, 'l2': 0.10686515347124315, 'dropout': 0.8221983458664543, 'tune_attn': True, 'num_layers': 1, 'attn_type': 'similarity', 'wordvec_source': 'gigavec', 'batch_size': 32, 'tune_wordvecs': False, 'lr': 0.00013997435717723325}
Using CUDA!
here
similarity
Building RNN Classifier...

[93m    Warning: no model found for 'en'[0m

    Only loading the 'en' tokenizer.

Retrieving Data from file: /home-nfs/siddsach/ml/Interpreting-Attention/interpreting_language/data/mpqa/mpqa_subj_labels.pickle...
Loading Vectors From Memory...
Using these vectors: ['gigavec']
Building Vocab...
[<torchtext.vocab.Vectors object at 0x7fc4735359b0>]
Getting Batches...
Created Iterator with 261 batches
Getting Batches...
Created Iterator with 87 batches
Building model...
similarity
Using Attention model with following args:
{'vectors': 
 0.0000  0.0000  0.0000  ...   0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000  ...   0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000  ...   0.0000  0.0000  0.0000
          ...             â‹±             ...          
 0.0000  0.0000  0.0000  ...   0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000  ...   0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000  ...   0.0000  0.0000  0.0000
[torch.FloatTensor of size 15284x300]
, 'num_classes': 2, 'rnn_dropout': 0.5183626113550769, 'input_size': 300, 'vocab_size': 15284, 'hidden_size': 300, 'attention_dim': 350, 'tune_attn': True, 'num_layers': 1, 'attn_type': 'similarity', 'train_word_vecs': False, 'cuda': True, 'batch_size': 32, 'dropout': 0.8221983458664543}
Traceback (most recent call last):
  File "tune_models.py", line 186, in <module>
    batch_size = args.batch_size, seq_len = args.seq_len)
  File "tune_models.py", line 67, in __init__
    exact_feval = True
  File "/home-nfs/siddsach/anaconda3/lib/python3.5/site-packages/GPyOpt/methods/bayesian_optimization.py", line 117, in __init__
    self._init_design_chooser()
  File "/home-nfs/siddsach/anaconda3/lib/python3.5/site-packages/GPyOpt/methods/bayesian_optimization.py", line 192, in _init_design_chooser
    self.Y, _ = self.objective.evaluate(self.X)
  File "/home-nfs/siddsach/anaconda3/lib/python3.5/site-packages/GPyOpt/core/task/objective.py", line 50, in evaluate
    f_evals, cost_evals = self._eval_func(x)
  File "/home-nfs/siddsach/anaconda3/lib/python3.5/site-packages/GPyOpt/core/task/objective.py", line 74, in _eval_func
    rlt = self.func(np.atleast_2d(x[i]))
  File "tune_models.py", line 119, in getError
    optimizer = trainer.start_train()
  File "/home-nfs/siddsach/ml/Interpreting-Attention/interpreting_language/classifier/attention_rnn/trainer.py", line 589, in start_train
    self.get_model(pretrained_weights, pretrained_args)
  File "/home-nfs/siddsach/ml/Interpreting-Attention/interpreting_language/classifier/attention_rnn/trainer.py", line 402, in get_model
    self.model = SelfAttentiveRNN(**args)
  File "/home-nfs/siddsach/ml/Interpreting-Attention/interpreting_language/classifier/attention_rnn/model.py", line 161, in __init__
    super(SelfAttentiveRNN, self).__init__(**kwargs)
  File "/home-nfs/siddsach/ml/Interpreting-Attention/interpreting_language/classifier/attention_rnn/model.py", line 38, in __init__
    .type(torch.cuda.FloatTensor), requires_grad=True) for i in range(num_states))
  File "/home-nfs/siddsach/ml/Interpreting-Attention/interpreting_language/classifier/attention_rnn/model.py", line 38, in <genexpr>
    .type(torch.cuda.FloatTensor), requires_grad=True) for i in range(num_states))
  File "/home-nfs/siddsach/anaconda3/lib/python3.5/site-packages/torch/_utils.py", line 38, in _type
    return new_type(self.size()).copy_(self, async)
  File "/home-nfs/siddsach/anaconda3/lib/python3.5/site-packages/torch/cuda/__init__.py", line 361, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: cuda runtime error (30) : unknown error at /opt/conda/conda-bld/pytorch_1513366702650/work/torch/lib/THC/generic/THCStorage.cu:58
